### ISSUE TITLE
could this be detected by game?

### ISSUE THREAD

**Issue by NoiseControllers** [PippoAe/PUBG_TRIGGR#1]

**Comment by PippoAe** [comment]
Hi NoiseController.
PUBG-Trigger doesn't give you any advantage in game.
It only scans the screen for kills and tries to extract the kill-message in order to trigger events in OBS.
Like  animations for headshot, monsterkill, pankill etc.

It doesn't read the games memory and works purely on OCR and Image-Analysis piggybacking on the OBS game-recorder's injection. (That's why you need to have OBS, so the PUBG-Trigger can get the images from there)

TLDR: No.
